[tool.black]
line-length = 110
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 110

[tool.ruff]
exclude = [
    "__init__.py",
    "bin",
    "doc",
    "version.py",
    "tests/.tests",
]
lint.ignore = [
    "E226",
    "E228",
    "N802",
    "N803",
    "N806",
    "N999",
]
line-length = 110
lint.select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "N",  # pep8-naming
    "W",  # pycodestyle
]
target-version = "py310"
lint.extend-select = [
    "RUF100", # Warn about unused noqa
]

[lint.pycodestyle]
max-doc-length = 79

[lint.pydocstyle]
convention = "numpy"
